# Site settings
title: 深几码谈
SEOTitle: liuxk99博客 | 深几的技术博客
#header-img: img/nav-home.jpg
email: liuxk99@gmail.com
description: "深几, liuxk99, Android博客, Android源码。"
keyword: "深几, liuxk99, Android博客, Android源码 。"
url: "http://liuxk99.github.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: true
weibo_username:     liuxk99
zhihu_username:     liu-xian-ke
linkedin_username:  thomas-liu-a5027318/
#google_userId:   101388994961262711072
#github_username:    liuxk99
#twitter_username:  liuxk99



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 15
paginate_path: "page:num"

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_
# valine comment settings
valine_comment.enable: true

# Duoshuo settings
duoshuo_username: liuxk99
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
#sidebar-about-description: "liuxk99"
sidebar-avatar: /images/liuxk99_wechat.jpg



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value


# hotpages
hotpages: [
    {
        title: "Android perf-cb",
        href:  "http://liuxk99.github.com/perf-cb"
    }
]

#money settings

#money-alipay: /images/about-me/
#money-weixin: /images/about-me/
money-description: 如果博客对您有所帮助，请分享给更多朋友，您的支持与认可将鼓励我坚持不懈的创作，谢谢您！
